application: n23
version: 1
runtime: python
api_version: 1

handlers:

- url: /blog
  script: apps/blog.py

- url: /blog/.*
  script: apps/blog.py

- url: /themes/.+
  script: apps/cache.py

- url: /static/.+
  script: apps/cache.py

- url: /phoneBook/(.*)
  script: apps/phoneBook.py

- url: /(.*)
  script: apps/main.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /google144e416da36fc6d1.html
  static_files: static/pages/google144e416da36fc6d1.html
  upload: static/pages/google144e416da36fc6d1.html

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: /_admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

#- url: /static
#  static_dir: static

#- url: /fetch.py
#  script: fetch.py

#- url: /zipme
#  script: zipme.py
